# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@main

    # Build the application
    - name: Setup .NET Core
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 5.0.101
        
    - name: Build xe-ideas
      run: |
        cd src/xe-ideas/
        dotnet build --configuration Release

    - name: Run Unit Tests
      run: |
        cd tests/xe-ideas.Tests/
        dotnet test